version: 2
updates:
  # Verify the Dockerfile in root for new images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # Target  PR’s for branch dev
    target-branch: "dev"
    commit-message:
      prefix: "deps:"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "tjibbevanderlaan"