name: Build & push dev image + PR

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # allow committing changes and creating tags
      pull-requests: write   # allow opening/updating pull-requests
      packages: write        # allow pushing the Docker image
    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v4

      # 2. Parse the Caddy version (e.g. 2.10.1) from the Dockerfile
      - name: Extract Caddy version
        id: vars
        run: |
          ver=$(grep -m1 -Po '(?<=FROM caddy:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
          echo "caddy_version=$ver" >> "$GITHUB_OUTPUT"

      # 3. Enable multi-arch builds
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # 4. Authenticate with Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and push the image tagged :dev
      - name: Build & push :dev tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy-digitalocean-dns:dev

      # 6. Create (or update) the promotion PR from dev → main
      - name: Create / update PR to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Promote Caddy v${{ steps.vars.outputs.caddy_version }} to main"
          body: |
            Automated pull request to promote **Caddy v${{ steps.vars.outputs.caddy_version }}**
            from `dev` to `main`.
          base: main
          branch: dev           # source branch
          draft: false
          delete-branch: false